apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "stack.zncdata.net/v1alpha1",
          "kind": "SparkHistory",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "spark-history-operator",
              "app.kubernetes.io/instance": "sparkhistory-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sparkhistory",
              "app.kubernetes.io/part-of": "spark-history-operator"
            },
            "name": "sparkhistory-sample"
          },
          "spec": {
            "image": {
              "pullPolicy": "IfNotPresent",
              "repository": "bitnami/spark",
              "tag": "latest"
            },
            "ingress": {
              "host": "sparkhistory-sample.local"
            },
            "nodeSelector": null,
            "persistence": {
              "accessModes": [
                "ReadWriteOnce"
              ],
              "size": "1Gi",
              "storageClass": "local-path"
            },
            "podSecurityContext": {
              "fsGroup": 1001
            },
            "replicas": 1,
            "resource": {
              "requests": {
                "cpu": "10m",
                "memory": "64Mi"
              }
            },
            "securityContext": {
              "runAsGroup": 1001,
              "runAsUser": 1001
            },
            "service": {
              "port": 10808,
              "type": "ClusterIP"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-08-10T05:39:39Z"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4-alpha
  name: spark-history-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SparkHistory is the Schema for the sparkhistories API
      displayName: Spark History
      kind: SparkHistory
      name: sparkhistories.stack.zncdata.net
      version: v1alpha1
  description: spark-history operator
  displayName: spark-history-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - stack.zncdata.net
          resources:
          - sparkhistories
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - stack.zncdata.net
          resources:
          - sparkhistories/finalizers
          verbs:
          - update
        - apiGroups:
          - stack.zncdata.net
          resources:
          - sparkhistories/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: spark-history-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: spark-history-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: spark-history-operator
          control-plane: controller-manager
        name: spark-history-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: docker-test.zncdata.net/zncdata-labs/spark-history-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: spark-history-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: spark-history-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - spark
  - spark-history
  - operator
  links:
  - name: Spark History Operator
    url: https://spark-history-operator.domain
  maintainers:
  - email: huagang.wang@zncdata.com
    name: wanghuagang
  maturity: alpha
  provider:
    name: zncdata-labs
    url: https://github.com/zncdata-labs/spark-history-operator
  version: 0.0.1
