apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "stack.zncdata.net/v1alpha1",
          "kind": "SparkHistoryServer",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "spark-k8s-operator",
              "app.kubernetes.io/instance": "sparkhistoryserver-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "sparkhistoryserver",
              "app.kubernetes.io/part-of": "spark-k8s-operator"
            },
            "name": "sparkhistoryserver-sample"
          },
          "spec": {
            "image": {
              "pullPolicy": "IfNotPresent",
              "repository": "bitnami/spark",
              "tag": "3.1.1"
            },
            "ingress": {
              "annotations": {
                "kubernetes.io/ingress.class": "nginx",
                "nginx.ingress.kubernetes.io/rewrite-target": "/"
              },
              "enabled": true,
              "host": "spark-history-server.example.com"
            },
            "persistence": {
              "accessMode": "ReadWriteOnce",
              "enable": true,
              "storageSize": "1Gi",
              "volumeMode": "Filesystem"
            },
            "replicas": 1,
            "resources": {
              "requests": {
                "cpu": "100m",
                "memory": "512Mi"
              }
            },
            "securityContext": {
              "fsGroup": 1000,
              "runAsUser": 1000
            },
            "service": {
              "port": 18080,
              "type": "ClusterIP"
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-11-03T07:01:15Z"
    operators.operatorframework.io/builder: operator-sdk-v1.32.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4-alpha
  name: spark-k8s-operator.v0.0.1-alpha
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SparkHistoryServer is the Schema for the sparkhistoryservers API
      displayName: Spark History Server
      kind: SparkHistoryServer
      name: sparkhistoryservers.stack.zncdata.net
      version: v1alpha1
  description: spark for k8s operator
  displayName: spark-k8s-operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2OCIgaGVpZ2h0PSIzNiIgdmlld0JveD0iMCAwIDY4IDM2Ij4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPHBhdGggZmlsbD0iI0UyNUExQyIgZD0iTTYyLjA2MSAxNy4yNDNjLS4wNTguMTIzLS4wODUuMTg2LS4xMTcuMjQ1LS44NSAxLjU5NC0xLjY5OCAzLjE5LTIuNTU1IDQuNzgtLjA4Ny4xNTktLjA3Ni4yNTQuMDQyLjM5IDEuMzUyIDEuNTU4IDIuNjk3IDMuMTIyIDQuMDQ0IDQuNjg1LjA0Ny4wNTQuMDkuMTEzLjEwOC4yMS0uMzk0LS4xMDEtLjc4OC0uMjAxLTEuMTgxLS4zMDQtMS42MzQtLjQyNy0zLjI2OC0uODUzLTQuOS0xLjI4NS0uMTUyLS4wNC0uMjIxLjAwMy0uMjk3LjEyOC0uOTI3IDEuNTI4LTEuODYgMy4wNTMtMi43OTIgNC41NzgtLjA0OC4wOC0uMS4xNTctLjIwMi4yMjMtLjA3NS0uNDA3LS4xNTItLjgxNC0uMjI1LTEuMjIxbC0uNzc3LTQuMzE0Yy0uMDI4LS4xNTYtLjA2Ny0uMzEtLjA4LS40NjctLjAxNC0uMTQ4LS4wOS0uMjAzLS4yMjctLjI0NS0xLjkyNS0uNTk2LTMuODQ4LTEuMTk4LTUuNzcyLTEuOC0uMDg0LS4wMjYtLjE2Ny0uMDYtLjI1Ny0uMTQxbDQuNzQ0LTEuODZjLS4wNTgtLjA0NS0uMDk2LS4wOC0uMTM4LS4xMDgtLjk4NC0uNjI4LTEuOTctMS4yNTMtMi45NS0xLjg4NC0uMTE4LS4wNzUtLjIxMS0uMDg2LS4zNDMtLjAyNy0xLjE3NS41MjEtMi4zNTUgMS4wMzMtMy41MzEgMS41NTItLjUyOS4yMzMtMS4wMDQuNTQyLTEuMzc0Ljk4OC0uODM3IDEuMDEtLjY3MiAyLjE1OC40NDMgMi44Ni4zNjUuMjMuNzguNDAxIDEuMTkyLjUzNCAxLjg4Ni42MDYgMy43NzkgMS4xOSA1LjY3IDEuNzc3LjE1OS4wNDkuMjMzLjExOS4yNjIuMjg4LjI1MiAxLjQ0LjUxNCAyLjg3Ny43NzYgNC4zMTUuMTQxLjc2OC4yMTYgMS41NTcuNTk1IDIuMjYuMTQ2LjI3Mi4zMi41MzcuNTI4Ljc2NC43NS44MjIgMS43OTkuODU0IDIuNTkzLjA3LjI2OC0uMjY0LjQ5OC0uNTc2LjY5OC0uODk1Ljg3NC0xLjQwNyAxLjczNS0yLjgyMyAyLjU5LTQuMjQuMTAyLS4xNjkuMTkzLS4yMDIuMzgtLjE1MyAyLjExLjU1OCA0LjIyMiAxLjEwNyA2LjMzMyAxLjY1Ny40MzYuMTE0Ljg3Ni4xNTUgMS4zMjMuMDczLjk3NC0uMTggMS40LS45MSAxLjA3LTEuODM4LS4xNS0uNDIyLS40MDktLjc4LS43LTEuMTE2LTEuNDczLTEuNzEtMi45NDQtMy40Mi00LjQyMi01LjEyNS0uMTIxLS4xNC0uMTI0LS4yNC0uMDQtLjM5Ni44ODItMS42NCAxLjc1Ni0zLjI4MyAyLjYzNC00LjkyNS4yMS0uMzkzLjM3LS44LjM3NS0xLjI1Mi4wMS0xLjAyNy0uNzUtMS44NjctMS43ODUtMi4wMTYtLjU4LS4wODQtMS4xMTguMDM4LTEuNjYuMjAzLTEuMzIzLjQwNC0yLjY0OC44LTMuOTc0IDEuMTkzLS4xMjMuMDM3LS4xNy4wODQtLjE5MS4yMTUtLjE1My45Mi0uMzE5IDEuODM4LS40OCAyLjc1Ny0uMDA0LjAyNS4wMDMuMDUyLjAwNy4xMDlsNC41NjMtMS4yNDIiIHRyYW5zZm9ybT0ibWF0cml4KDEgMCAwIC0xIDAgMzUuOTc0KSIvPgogICAgICAgIDxwYXRoIGZpbGw9IiNGRkYiIGQ9Ik01OS40ODMgMy44NDFjLTEuMTkzLjAwMi0yLjM4Ni4wMDgtMy41OC4wMDMtLjE1NyAwLS4yNDYuMDQ1LS4zMzQuMTc3LTEuNDEyIDIuMTIyLTIuODMgNC4yMzktNC4yNDggNi4zNTctLjA0NS4wNjgtLjA5My4xMzMtLjE3NC4yNDZsLS45MDItNi43NjdoLTMuMTI0Yy4wMzcuMy4wNjkuNTkuMTA3Ljg4LjMwNSAyLjI5Ni42MTEgNC41OTQuOTE4IDYuODkuMjkyIDIuMTk1LjU4MyA0LjM5Ljg4IDYuNTg1LjAwOS4wNjUuMDUzLjE0OC4xMDcuMTgzIDEuMDc1LjY5IDIuMTU0IDEuMzc2IDMuMjMyIDIuMDYyLjAxNi4wMS4wMzguMDExLjA5NC4wMjdsLS45NzQtNy4zMjQuMDM4LS4wMjYgNS4xMTMgNS41OS4xMzYtLjc3MmMuMTIxLS42OTguMjM3LTEuMzk2LjM2Ny0yLjA5Mi4wMjYtLjE0LS4wMTEtLjIyOC0uMTA2LS4zMjUtMS4wOTQtMS4xMy0yLjE4NS0yLjI2My0zLjI3Ni0zLjM5NmwtLjE0Ny0uMTU5Yy4wMzUtLjA1NS4wNjQtLjEwOC4xLS4xNTdsNS42NDctNy44MTRjLjAzNC0uMDQ4LjA4My0uMDg1LjEyNi0uMTI3di0uMDRNMjIuNDU1IDEwLjYxNGMtLjA0OC4yNC0uMDgyLjU5My0uMTkuOTIyLS41MjMgMS41OTItMi4xOCAyLjQ2NS0zLjg5NCAyLjA3MS0xLjg4LS40MzEtMy4yMjQtMS44OS0zLjQxOC0zLjc4Mi0uMTQ0LTEuNC42Mi0yLjc0OSAyLjA0MS0zLjI1NSAxLjE0NS0uNDA4IDIuMjQ3LS4yMzcgMy4yNy4zNjggMS4zNTguODAzIDIuMDkzIDEuOTk1IDIuMTkgMy42NzZ6bS04LjI1OC01LjkxN2MtLjA5My0uNjg1LS4xODItMS4zMy0uMjY4LTEuOTc3LS4xMTQtLjg1OC0uMjI4LTEuNzE3LS4zMzgtMi41NzYtLjAxMy0uMS0uMDQ0LS4xNDUtLjE1My0uMTQ0LS44NTguMDAzLTEuNzE2LjAwMy0yLjU3NC4wMDQtLjAyIDAtLjAzOS4wMS0uMDg1LjAyMy4wNTEuNDA2LjEwMi44MTIuMTU2IDEuMjE4LjE5IDEuNDI1LjM3OCAyLjg0OS41NyA0LjI3My4yMiAxLjYyOC4zOTQgMy4yNjQuNjc1IDQuODgyLjQ5OSAyLjg2NCAyLjk2MiA1LjMzMyA1Ljg1NCA1Ljk0OCAxLjY3Ni4zNTYgMy4yOC4xOTEgNC43NDMtLjc0IDEuNDYtLjkyNyAyLjI5Ny0yLjI3MyAyLjQ4OC0zLjk2Ny4yNy0yLjM5NC0uNjI0LTQuMzgyLTIuMzQ4LTYuMDI2LTEuMTMyLTEuMDgtMi40ODctMS43NjYtNC4wNS0xLjk5OC0xLjYxLS4yMzktMy4xMjQuMDI2LTQuNDgyLjk2Mi0uMDUuMDM0LS4xMDMuMDY0LS4xODguMTE4TTEyLjc5OCAxOC4zMDhsLTIuODIxLTIuMDcxYy0uMTUuMjMzLS4yODUuNDY2LS40NDIuNjgzLS40MDQuNTU3LS45MDYuOTczLTEuNjM3IDEuMDI0LS42MDcuMDQyLTEuMTI2LS4xNTYtMS41NC0uNTk3LS4zNy0uMzk1LS40MTgtLjk1Ny0uMDcyLTEuNDAzLjM4LS40OS43OTYtLjk1NiAxLjIyMS0xLjQxMS43MDUtLjc1MyAxLjQ0Mi0xLjQ3OCAyLjE0Mi0yLjIzNi42MzctLjY4OSAxLjE0NC0xLjQ2MiAxLjMwMS0yLjQwNC4xODctMS4xMi0uMDQtMi4xODctLjU3Ny0zLjE3MS0uOTk0LTEuODIyLTIuNTYtMi44OC00LjYyNi0zLjIxLS45MTMtLjE0Ni0xLjgyMy0uMTE3LTIuNzE0LjE0MkMxLjg1MSAzLjk5NyAxLjAzIDQuNzYuNSA1Ljg0LjMxMyA2LjIyLjE3IDYuNjI0IDAgNy4wMzNsMy4wNiAxLjYxNWMuMDM1LS4wODQuMDYtLjE1NC4wOTMtLjIyLjE3NC0uMzQzLjMxNy0uNzA3LjUzMi0xLjAyMy42MzktLjkzNyAxLjY3LTEuMjIyIDIuNzE4LS43Ni4yNjguMTIuNTI3LjI4OC43NDguNDguNjc1LjU5MS44MDEgMS40MTMuMzAyIDIuMTU2LS4yODcuNDI3LS42NDYuODEtLjk5NSAxLjE5My0uODM1LjkxNC0xLjcwNCAxLjgtMi41MiAyLjczLS41NjEuNjQyLS45NDMgMS4zOS0xLjA2NCAyLjI1LS4xMzIuOTM4LjA1OCAxLjgyMy41NTMgMi42MTMgMS4yMyAxLjk2MyAzLjAyIDIuOTg1IDUuMzg1IDIuOSAxLjM0OC0uMDQ4IDIuNDIyLS42NyAzLjI1Ni0xLjcwMy4yNDYtLjMwNi40NzgtLjYyNC43My0uOTU2TTM1LjY0OCA3Ljc2N2MtLjE1Ni0xLjE4My0uMzA0LTIuMzA3LS40NTgtMy40My0uMDA4LS4wNTctLjA1My0uMTM0LS4xMDItLjE1Ny0yLjMyOS0xLjA2My01LjM5NS0uOTE1LTcuMzA3IDEuMjI3LTEuMDI4IDEuMTUtMS40NTkgMi41MTYtMS4zOTQgNC4wMzYuMTQ5IDMuNTE3IDMuMTA1IDYuNTg3IDYuNjQxIDcuMDE2IDIuMDY2LjI1MSAzLjg3OC0uMyA1LjI3Ny0xLjg4Mi45NTMtMS4wNzggMS4zOTQtMi4zNjYgMS4zMjktMy43ODctLjA0My0uOTM4LS4xOTItMS44NzMtLjMxLTIuODA3LS4xNjgtMS4zMjMtLjM1Mi0yLjY0NS0uNTI5LTMuOTY3LS4wMDYtLjA0Ny0uMDE2LS4wOTQtLjAyNi0uMTUzaC0yLjc4NmMuMDM3LjMwNC4wNzEuNjAxLjExLjg5OC4yMDIgMS41MjcuNDI0IDMuMDUyLjYgNC41ODIuMTEuOTUyLjA0MSAxLjg5OC0uNCAyLjc4LS40Ny45MzktMS4yNTkgMS40MzUtMi4yOTUgMS41NDMtMi4xNDUuMjI0LTQuMTg2LTEuMjQ2LTQuNjQzLTMuMzI4LS4zMDItMS4zNzQuMTc0LTIuNjkxIDEuMjg0LTMuNDIgMS4wODEtLjcxIDIuMjQtLjcxMiAzLjQxOC0uMjUxLjU5OC4yMzMgMS4xMDcuNjAyIDEuNTkxIDEuMU00Ny4zNzggMTYuMTkybC0uMzgtMi44NDhjLS41OSAwLTEuMTY3LjAwMy0xLjc0NC0uMDAyLS40NjgtLjAwMy0uODk1LS4zMDEtMS4wMzYtLjczMi0uMDU1LS4xNjgtLjA3NS0uMzQ5LS4wOTktLjUyNi0uMjkzLTIuMTg3LS41ODMtNC4zNzQtLjg3NC02LjU2Mi0uMDc0LS41NTEtLjE0NS0xLjEwMy0uMjE5LTEuNjYzaC0yLjg5OWMuMDU0LjQyLjEwNS44MjguMTYgMS4yMzQuMTg4IDEuNDE4LjM3NiAyLjgzNS41NjcgNC4yNTIuMTY1IDEuMjI2LjMxMiAyLjQ1NS41MDcgMy42NzcuMjYgMS42MzggMS45MTIgMy4wOTMgMy41ODggMy4xNjQuOC4wMzUgMS42MDIuMDA2IDIuNDI5LjAwNiIgdHJhbnNmb3JtPSJtYXRyaXgoMSAwIDAgLTEgMCAzNS45NzQpIi8+CiAgICAgICAgPHBhdGggZmlsbD0iI0ZGRiIgZmlsbC1ydWxlPSJub256ZXJvIiBkPSJNNjIuOSAzLjg1OXYxLjIwN2gtLjAwNmwtLjQ4LTEuMjA3aC0uMTU0bC0uNDggMS4yMDdoLS4wMDdWMy44NmgtLjI0MnYxLjQ0NmguMzczbC40MzgtMS4wOTkuNDMgMS4wOTloLjM3VjMuODU5aC0uMjQxem0tMi4xMjcgMS4yNTNWMy44NTloLS4yNDJ2MS4yNTNoLS40NnYuMTkzaDEuMTZ2LS4xOTNoLS40NThNMTYuNjgyIDIwLjMzOWguNzJsLS4xNyAxLjA3My0uNTUtMS4wNzN6bS44MzItLjY5NGgtMS4xOTZsLS4zOC0uNzM0aC0uODQ3bDEuODY4IDMuNDQzaC44MTdsLjYzNi0zLjQ0M2gtLjc4NWwtLjExMy43MzRNMjEuNzkzIDIxLjY2aC0uNDI2bC0uMTQzLS43OTRoLjQyNWMuMjU3IDAgLjQ2My4xNjYuNDYzLjQ4IDAgLjIwOC0uMTMuMzE0LS4zMTkuMzE0em0tMS4wMzIuNjk0aDEuMTJjLjU4NSAwIC45OTUtLjM0NS45OTUtLjkzNyAwLS43NDQtLjUzNC0xLjI0NS0xLjI5My0xLjI0NUgyMS4xbC0uMjI2LTEuMjZoLS43MjhsLjYxNSAzLjQ0Mk0yNS4zNTIgMjAuMzM5aC43MTlsLS4xNyAxLjA3My0uNTUtMS4wNzN6bS44MzEtLjY5NGgtMS4xOTVsLS4zOC0uNzM0aC0uODQ3bDEuODY4IDMuNDQzaC44MTZsLjYzNy0zLjQ0M2gtLjc4NmwtLjExMy43MzRNMzAuOTEyIDE5LjAzM2MtLjI0Ni0uMTExLS41MTgtLjE3OC0uNzktLjE3OC0uOTI0IDAtMS41MDUuNjg0LTEuNTA1IDEuNTQgMCAxLjA5My45MzUgMi4wMTUgMi4wNDQgMi4wMTUuMjc3IDAgLjUyOC0uMDY2LjczMy0uMTc3bC0uMTAyLS44MjZjLS4xNTQuMTY3LS40LjI4NC0uNzA5LjI4NC0uNjM2IDAtMS4yLS41NjgtMS4yLTEuMjI1IDAtLjUwMi4zMTgtLjg5Mi44Mi0uODkyLjMwOSAwIC42MDYuMTE3LjgwNi4yNzlsLS4wOTctLjgyTTM1LjM2NiAyMC4yOThMMzMuODQ3IDIwLjI5OCAzMy42IDE4LjkxMSAzMi44NzIgMTguOTExIDMzLjQ4NyAyMi4zNTQgMzQuMjE2IDIyLjM1NCAzMy45NyAyMC45OTIgMzUuNDg5IDIwLjk5MiAzNS43MzUgMjIuMzU0IDM2LjQ2NCAyMi4zNTQgMzUuODQ5IDE4LjkxMSAzNS4xMiAxOC45MTEgMzUuMzY2IDIwLjI5OE0zOC4wMzkgMTguOTExTDM4LjY1NSAyMi4zNTQgNDAuNTkgMjIuMzU0IDQwLjQ2NyAyMS42NiAzOS4yNiAyMS42NiAzOS4xMzggMjAuOTkyIDQwLjI0NiAyMC45OTIgNDAuMTIzIDIwLjI5OCAzOS4wMTQgMjAuMjk4IDM4Ljg5MSAxOS42MDUgNDAuMDk3IDE5LjYwNSAzOS45NzQgMTguOTExIDM4LjAzOSAxOC45MTEiIHRyYW5zZm9ybT0ibWF0cml4KDEgMCAwIC0xIDAgMzUuOTc0KSIvPgogICAgPC9nPgo8L3N2Zz4K
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - stack.zncdata.net
          resources:
          - sparkhistoryservers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - stack.zncdata.net
          resources:
          - sparkhistoryservers/finalizers
          verbs:
          - update
        - apiGroups:
          - stack.zncdata.net
          resources:
          - sparkhistoryservers/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: spark-k8s-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: operator-lifecycle-manager
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: spark-k8s-operator
          app.kubernetes.io/part-of: spark-k8s-operator
          control-plane: controller-manager
        name: spark-k8s-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/component: manager
                app.kubernetes.io/created-by: operator-lifecycle-manager
                app.kubernetes.io/instance: controller-manager
                app.kubernetes.io/managed-by: kustomize
                app.kubernetes.io/name: spark-k8s-operator
                app.kubernetes.io/part-of: spark-k8s-operator
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: docker.io/bitnami/kube-rbac-proxy:0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/zncdata/spark-k8s-operator:0.0.1-alpha
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: spark-k8s-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: spark-k8s-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - spark
  - k8s
  links:
  - name: Spark Website
    url: https://spark.apache.org/
  - name: Repository
    url: https://github.com/zncdata-labs/spark-k8s-operator
  - name: icon
    url: https://spark.apache.org/favicon.ico
  maintainers:
  - email: huagang.wang@zncdata.com
    name: wanghuagang
  maturity: alpha
  provider:
    name: zncdata-labs
    url: https://github.com/zncdata-labs
  version: 0.0.1-alpha
