apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: spark-history-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SparkHistory is the Schema for the sparkhistories API
      displayName: Spark History
      kind: SparkHistory
      name: sparkhistories.stack.zncdata.net
      version: v1alpha1
  description: spark-history operator
  displayName: spark-history-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - spark
  - spark-history
  - operator
  links:
  - name: Spark History Operator
    url: https://spark-history-operator.domain
  maintainers:
  - email: huagang.wang@zncdata.com
    name: wanghuagang
  maturity: alpha
  provider:
    name: zncdata-labs
    url: https://github.com/zncdata-labs/spark-history-operator
  version: 0.0.0
