apiVersion: stack.zncdata.net/v1alpha1
kind: SparkHistory
metadata:
  labels:
    app.kubernetes.io/name: sparkhistory
    app.kubernetes.io/instance: sparkhistory-sample
    app.kubernetes.io/part-of: spark-history-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spark-history-operator
  name: sparkhistory-sample
spec:
  # TODO(user): Add fields here
