apiVersion: stack.zncdata.net/v1alpha1
kind: SparkHistory
metadata:
  labels:
    app.kubernetes.io/name: sparkhistory
    app.kubernetes.io/instance: sparkhistory-sample
    app.kubernetes.io/part-of: spark-history-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spark-history-operator
  name: sparkhistory-sample
spec:
  replicas: 2
  image:
    repository: bitnami/spark
    tag: latest
    pullPolicy: IfNotPresent
  resource:
    requests:
      cpu: 10m
      memory: 64Mi
  service:
    type: ClusterIP
    port: 10808
  podSecurityContext:
    fsGroup: 1001
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
  nodeSelector:
  persistence:
    storageClass: local-path
    accessModes:
    - ReadWriteOnce
    size: 1Gi
  ingress:
    host: sparkhistory-sample.local
